name: Publish to Itch.io

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Buscamos específicamente el zip de Windows que subiste
      - name: Download Release Assets
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: "Pixel.Bash.Windows.zip"
          out-heading: false

      - name: Upload to Itch.io via Butler
        uses: Ayowel/butler-to-itch@v1
        with:
          butler_key: ${{ secrets.ITCH_API_KEY }}  # Se pone aquí dentro de "with"
          itch_user: "csprats"
          itch_game: "pixel-bash"                  # Sin el "csprats/" delante
          files: "Pixel.Bash.Windows.zip"           # En lugar de "package"
