name: Publish to Itch.io

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Buscamos específicamente el zip de Windows que subiste
      - name: Download Release Assets
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: "Pixel.Bash.Windows.zip"
          out-heading: false

      - name: Upload to Itch.io via Butler
        uses: josephbmanley/itchio-butler-action@v1.1.2
        with:
          itch_game: "csprats/pixel-bash"
          itch_user: "csprats"
          package: "Pixel.Bash.Windows.zip"
          channel: "windows"
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_API_KEY }}
